# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sintomas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sintomas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esintomas.proto\x12\x08sintomas\"!\n\rListaSintomas\x12\x10\n\x08sintomas\x18\x01 \x03(\t\"@\n\x13RespostaDiagnostico\x12\x13\n\x0b\x64iagnostico\x18\x01 \x01(\t\x12\x14\n\x0crecomendacao\x18\x02 \x01(\t2U\n\x0fSintomasService\x12\x42\n\x08\x41nalisar\x12\x17.sintomas.ListaSintomas\x1a\x1d.sintomas.RespostaDiagnosticob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sintomas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTASINTOMAS']._serialized_start=28
  _globals['_LISTASINTOMAS']._serialized_end=61
  _globals['_RESPOSTADIAGNOSTICO']._serialized_start=63
  _globals['_RESPOSTADIAGNOSTICO']._serialized_end=127
  _globals['_SINTOMASSERVICE']._serialized_start=129
  _globals['_SINTOMASSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
