# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sintomas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sintomas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esintomas.proto\"!\n\rSintomasInput\x12\x10\n\x08sintomas\x18\x01 \x03(\t\"5\n\x08Resposta\x12\x13\n\x0b\x64iagnostico\x18\x01 \x01(\t\x12\x14\n\x0crecomendacao\x18\x02 \x01(\t28\n\x0fSintomasService\x12%\n\x08\x41nalisar\x12\x0e.SintomasInput\x1a\t.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sintomas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINTOMASINPUT']._serialized_start=18
  _globals['_SINTOMASINPUT']._serialized_end=51
  _globals['_RESPOSTA']._serialized_start=53
  _globals['_RESPOSTA']._serialized_end=106
  _globals['_SINTOMASSERVICE']._serialized_start=108
  _globals['_SINTOMASSERVICE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
